.travis.yml:
  env:
    global:
    - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    - GLIDE_HOME="${HOME}/.glide"
    matrix:
    - TEST_TYPE=small
    - TEST_TYPE=large
  matrix:
    exclude:
    - go: 1.6.x
      env: TEST_TYPE=large
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: ObH9rKzsgHC3LxK5sRD1lgcvkEyaeIEC91NrSpR1IpFYVqH7+GpayTcwpjqKX6dAD4Ljwf9yuVeqwWdiaPXxxhh8h2V4YeXtupkbUNCUjeUXj5gEizNPg0jEqRqANwoU6niOVYswnRZiXDAjhlyqszHrKIZ4kavBpRDZLcLOufJ9RCqMrs7L94mz7wa4gmt0S2N7dZNxdW5fubkI23CExasXeuih057F4FAsu8gzFyYINi2tNE+z96Aagmh1Xggy4oEx/3Mc4Duk5zOSUwO+dh6lUxJ0nGOmF2h1AYVgLe+mNGVQIfRAAmxRFMjyYsug3HxItLWja3c1oF/fbylbYzlIbSUIdEuoV5TDhWmK3Ln3fKgkY3HO4xypHM9wWqKNfBoVugDF702J9DtJYyKphLPzcStbVme1VgGF+g7d4n40R8MEBD6c5AoT/DvKq9yRnMlIfc579eBNNVPaZZhm6QuHMTTiBH2utFr5BjgEnNz4z7b2yE17v6rgaiiksU7Mj8M39H8+c5+TgfSuvrSFCQJhoP4ujr+q78b4Mnp+WI6g3EuK+a8DF6/QqIBcVtJxEbQL/a4Aa5eF+tgRGXIfFQrCAqfFJV8qimVQggg2gTCsHIEomJgibjZEphfCZLXosCvS6mG31M5nUcWjYf2R68683MW3j/r+WlYBXK73TsU=
    api_key:
      secure: Nv3ZD/WL+AyQhs7tV3RMZS6EYGPzZXHjPdA+0Dg6Pq7wAUpqRIlwRAX5iD5rxXbfBb5daTeACbvxsWpDGKxwLaKykcA32mKJpff6At7WWql16U152flg3Z1eOC+wFT0JgpZQ8WThSsW/zqEhgiSfNSAC2emzJ1WqCmQ2URPkUjdzYJ6oyG07U7dDDtNPKyt/qOByQ/2981pFErYcoHhA+CK4oFsxEYzy7cVruj0KOqkP3xDHgjS6fOPQbr5p69gSfpBN4/CcGQ82UEsmEghLUbAAdo8t3qzuGR7vtA5dLheQfMCwHv+JdkvoZFVI0cu/vKVG69jGPq1DRzwalN/ZOx4WzkgGyN9EoDZ4r7oSf55iyd+O8eM7ND4WoxWPivzALYfmKnTkXm4V11JAAe9yiNWadLT5//P3kEfx2HfTFhXhsARqvwcnw26ypzDctFqcOKiTaenpaPqr5bkQXAYBUKS2fPYoiPmou6vyahBuen/NVu1Kcc+xyZvdAwB5KwJvQwBAbrtBR1REk0QgWcepq+kZjH68vS1191XGezb9v+OaXy35DiXKnCqv3fXrE9tNXtEKNG9MOwf6ykmaYBzN/axsWAhlBqc3Qg30s5bBQdqzSRQ9ERQ6TQoUfXiBLm81clnrvuWGmZ+r9Efm4O++6kUvBcqmq0OJEajSkW/6eYY=
scripts/deps.sh:
  packages:
    - github.com/smartystreets/goconvey # NOTE: this should be moved to godep/glide
    - github.com/stretchr/testify/mock
